backend:
  name: github
  repo: codestates/studystates-client
  branch: dev

media_folder: static/img
public_folder: /img

collections:
  - name: "topics"
    label: "Topics"
    folder: "src/pages/topics"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "detail-page",
        }
      - { label: "스터디명", name: "title", widget: "string" }
      - { label: "스터디 소개", name: "description", widget: "string", hint: "1줄 이내 간략하게 핵심만, 유저들의 관심을 끌만한 카피를 작성해주세요"}
      - { label: "메인 이미지", name: "image", widget: "image" }
      - {
          label: "스터디 기본정보",
          name: "info",
          widget: "object",
          fields: 
            [
              { label: "스터디 시작일", name: "startDate", widget: "date" },
              { label: "스터디 종료일", name: "endDate", widget: "date" },
              { label: "기간 (단위: 주)", name: "period", widget: "string", hint: "주 단위로 작성해주세요. 예시) 4주"},
              { label: "스터디 미팅 (단위: 회)", name: "totalMeeting", widget: "string", hint: "회 단위로 작성해주세요. 예시) 4회"},
              { label: "스터디 미팅 일정", name: "schedule", widget: "string", hint: "양식에 맞게 작성해주세요. 예시) 4/29, 5/13, 5/27, 6/10"},
              { 
                label: "스터디 미팅 시간", 
                name: "studyTimes", 
                widget: "object", 
                fields:
                  [
                    { label: "빈도", name: "frequency", widget: "select", options: ["매주", "격주"]},
                    { label: "요일", name: "dayOfWeek", widget: "select", options: ["월요일", "화요일", "수요일", "목요일", "금요일", "토요일", "일요일"]},
                    { label: "시간", name: "time", widget: "string", hint: "양식에 맞게 작성해주세요. 예시) 20:00 - 21:00"}
                  ]
              },
              { label: "가격 (단위: 원)", name: "price", widget: "number", hint: "원 단위로 작성하되 숫자로만 작성해주세요. 예시) 50000"},
              { label: "특이사항", name: "note", widget: "string", required: "false", hint: "특이사항이 있는 경우에만 작성해주세요."},
              { 
                label: "안내사항", 
                name: "details", 
                widget: "text", 
                default: "최소 인원 4명 이상 모집되지 않는 경우, 시작일이 변경될 수 있습니다.\n
                          스터디 시작 1일 전까지 전액 환불 가능합니다. (자세한 사항은 FAQ 참고)\n   
                          유료 컨텐츠를 기반으로 진행되는 경우, 스터디 참가자 분들께 제공됩니다.\n
                          커리큘럼은 스터디원의 요구나 학습 진행 속도에 따라 변경될 수 있습니다.",
                hint: "추가로 작성할 안내사항이 있는 경우, '\\n' 을 사용하여 문장 구분을 해주세요."
              }
            ]
        }
      - { 
          label: "인트로", 
          name: "intro", 
          widget: "object", 
          fields:
            [
              { label: "스터디 상세소개", name: "text", widget: "text", hint: "스터디 소개 글을 2~3줄로 작성해주세요"},
              { 
                label: "학습목표", 
                name: "objectives", 
                widget: "list", 
                fields:
                  [
                    { label: "연관 이미지", name: "image", widget: "image"},
                    { label: "내용", name: "text", widget: "string"}
                  ],
                hint: "반드시 3개까지 작성해주세요"
              },
              {
                label: "참여대상",
                name: "targets",
                widget: "list",
                fields:
                  [
                    { label: "대상", name: "title", widget: "string", hint: "핵심 한 줄로 작성해 주세요"},
                    { label: "상세내용", name: "content", widget: "text", hint: "좀 더 구체적으로 2~3줄 작성해 주세요"}
                  ],
                hint: "반드시 3개까지 작성해주세요"
              }
            ]
        }
      - {
        label: "스터디 파트너",
        name: "partner",
        widget: "object",
        fields:
          [
            { label: "프로필 사진", name: "image", widget: "image"},
            { label: "이름", name: "name", widget: "string"},
            { label: "현재 직업", name: "currentJob", widget: "string"},
            { label: "경력사항", name: "career", widget: "list", hint: "경력사항 3~5개를 콤마로 구분하여 나열해주세요"},
            { 
              label: "Q&A", 
              name: "qna", 
              widget: "list",
              fields:
                [
                  { label: "Q", name: "Q", widget: "string"},
                  { label: "A", name: "A", widget: "text"}
                ],
              hint: "다음 기본 질문 3가지를 Q 항목에 입력하시고 A 항목에 답변해 주세요. 기타 질문으로 변경 가능합니다. | Q. 스터디 기획 의도는 무엇인가요? | Q. 이 스터디의 차별화된 특징은 무엇인가요? | Q. 스터디 참여자들에게 한 마디 해주세요!"
            }
          ]
      }
      - {
        label: "커리큘럼",
        name: "curriculum",
        widget: "object",
        fields:
          [
            { label: "교재 및 컨텐츠", name: "intro", widget: "string", hint: "예시) 본 스터디는 ~~~ 강좌를 중심으로 필요한 자료들을 추가하며 진행합니다."},
            { label: "주차별 주제", name: "weeklyTopics", widget: "list", hint: "여러 문장을 작성 시, '\\n' 을 사용하여 문장 구분을 해주세요."}
          ]
      }
      - {
        label: "대표 키워드",
        name: "keywords",
        widget: "list",
        hint: "대표 키워드 3~5개를 콤마로 구분하여 나열해주세요"
      }
      - {
        label: "스터디 오픈 여부",
        name: "open",
        widget: "boolean",
        default: true
      }
      - {
        label: "메인 노출 여부",
        name: "main",
        widget: "boolean",
        default: false
      }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Carousel,
              name: carousel,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Header, name: header, widget: string },
                  { label: Caption, name: caption, widget: string },
                  { label: AltText, name: altText, widget: string },
                ],
            }
          - {
              label: Carousel,
              name: carousel,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  {
                    label: Logo,
                    name: logo,
                    widget: list,
                    fields: [{ label: Image, name: image, widget: image }],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Image, name: image, widget: image },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Main Pitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Content,
                    name: content,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Title, name: title, widget: string },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
      - file: "src/pages/faq/index.md"
        label: "FAQ Page"
        name: "faq"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "faq-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
