backend:
  name: github
  repo: codestates/studystates-client
  branch: dev

media_folder: static/img
public_folder: /img

collections:
  - name: "topics"
    label: "Topics"
    folder: "src/pages/topics"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "detail-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: Image, name: image, widget: image }
      - {
          label: Info,
          name: info,
          widget: object,
          fields: 
            [
              { label: "Start Date", name: "startDate", widget: "date" },
              { label: "End Date", name: "endDate", widget: "date" },
              { label: "Period", name: "period", widget: "string"},
              { label: "Total Meeting", name: "totalMeeting", widget: "string"},
              { label: "Schedule", name: "schedule", widget: "string", hint: "양식에 맞게 작성해주세요. 예시) 4/29, 5/13, 5/27, 6/10"},
              { 
                label: "Study Times", 
                name: "studyTimes", 
                widget: "object", 
                fields:
                  [
                    { label: "Frequency", name: "frequency", widget: "select", options: ["매주", "격주"]},
                    { label: "Day of Week", name: "dayOfWeek", widget: "select", options: ["월요일", "화요일", "수요일", "목요일", "금요일", "토요일", "일요일"]},
                    { label: "Time", name: "time", widget: "string", hint: "양식에 맞게 작성해주세요. 예시) 20:00 - 21:00"}
                  ]
              },
              { label: "Price", name: "price", widget: "number"},
              { label: "Note", name: "note", widget: "string", required: "false"},
              { label: "Details", name: "details", widget: "text"}
            ]
        }
      - { 
          label: "Intro", 
          name: "intro", 
          widget: "object", 
          fields:
            [
              { label: "Text", name: "text", widget: "text"},
              { 
                label: "Objectives", 
                name: "objectives", 
                widget: "list", 
                allow_add: false, 
                fields:
                  [
                    { label: "Image", name: "image", widget: "image"},
                    { label: "Text", name: "text", widget: "string"}
                  ]
              },
              {
                label: "Targets",
                name: "targets",
                widget: "list",
                allow_add: false,
                fields:
                  [
                    { label: "Title", name: "title", widget: "string"},
                    { label: "Content", name: "content", widget: "string"}
                  ]
              }
            ]
        }
      - {
        label: "Parnter",
        name: "partner",
        widget: "object",
        fields:
          [
            { label: "Image", name: "image", widget: "image"},
            { label: "Name", name: "name", widget: "string"},
            { label: "Current Job", name: "currentJob", widget: "string"},
            { label: "Career", name: "career", widget: "list"},
            { 
              label: "QnA", 
              name: "qna", 
              widget: "list",
              fields:
                [
                  { label: "Q", name: "Q", widget: "string"},
                  { label: "A", name: "A", widget: "string"}
                ]
            }
          ]
      }
      - {
        label: "Curriculum",
        name: "curriculum",
        widget: "object",
        fields:
          [
            { label: "Intro", name: "intro", widget: "string"},
            { label: "Weekly Topics", name: "weeklyTopics", widget: "Text", hint: "여러 문장을 작성 시, \n 을 사용하여 문장 구분을 해주세요."}
          ]
      }
      - {
        label: "Keywords",
        name: "keywords",
        widget: "list",
      }
      - {
        label: "Open",
        name: "open",
        widget: "boolean",
        default: true
      }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Carousel,
              name: carousel,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Header, name: header, widget: string },
                  { label: Caption, name: caption, widget: string },
                  { label: AltText, name: altText, widget: string },
                ],
            }
          - {
              label: Carousel,
              name: carousel,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  {
                    label: Logo,
                    name: logo,
                    widget: list,
                    fields: [{ label: Image, name: image, widget: image }],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Image, name: image, widget: image },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Content,
                    name: content,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Title, name: title, widget: string },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
      - file: "src/pages/faq/index.md"
        label: "FAQ Page"
        name: "faq"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "faq-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
